import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fixture, snapshot, MANAGED_PATHS } from "./helpers.mjs";
test("exact packed artifact: allowlist, install, update, doctor and no writes on dry-run",async t=>{
 const tarball=process.env.BRIDGECODE_TARBALL;
 assert.ok(tarball,"Use npm run test:release; exact artifact is mandatory, never skipped");
 assert.ok((await stat(tarball)).isFile());
 const names=JSON.parse(process.env.BRIDGECODE_PACK_FILES||"[]");
 for(const p of [...MANAGED_PATHS,"package.json","bin/bridgecode.mjs","hooks/bridgecode-turn.mjs","legacy/4.1.0.json","legacy/4.3.0.json"])assert.ok(names.includes(p),p);
 assert.equal(names.some(p=>/^(test|scripts|agentic|\.github)\//.test(p)||/primitives|\.npmrc|package-lock/.test(p)),false);
 const root=await fixture(t,"bridgecode-artifact-project-"),host=await fixture(t,"bridgecode-artifact-host-");
 const npm=process.env.npm_execpath;assert.ok(npm);
 execFileSync(process.execPath,[npm,"install","--prefix",host,"--ignore-scripts","--no-audit","--no-fund","--package-lock=false",tarball],{encoding:"utf8"});
 const cli=path.join(host,"node_modules/@bridgecode/cli/bin/bridgecode.mjs");
 const invoke=(...args)=>JSON.parse(execFileSync(process.execPath,[cli,...args,"--project",root,"--json"],{encoding:"utf8"}));
 const before=await snapshot(root);assert.ok(invoke("install","--dry-run").changes.length);assert.deepEqual(await snapshot(root),before);
 assert.equal(invoke("install").verified,true);
 const installed=await snapshot(root);assert.equal(invoke("update").changes.length,0);assert.deepEqual(await snapshot(root),installed);
 assert.equal(invoke("doctor").ok,true);
});
